/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chaostocosmos.chaosdashboard;

import org.chaostocosmos.chaosgraph.awt2d.AreaGraph;
import org.chaostocosmos.chaosgraph.awt2d.GraphExample1;

public class App {

    GraphExample1 ag;

    public String getGreeting() {
        this.ag = new GraphExample1();
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
